<h1 style="text-align:center; font-weight:bold;"> NumPy </h1>
<hr style="border: none; height: 3px; 
             background: linear-gradient(to right, #6a11cb, #2575fc);">
<div>

  <h4>What is NumPy?</h4>
  <p>
    <b>NumPy (Numerical Python)</b> is a powerful Python library used for 
    fast mathematical computations and working with arrays. It allows us to handle large datasets efficiently and perform complex calculations with minimal code.
  </p>

  <h4>Python List vs NumPy Array - </h4>
  <ul>
    <li><b>Python List:</b> Basic tool (slower, limited operations)</li>
    <li><b>NumPy Array:</b> Advanced tool (faster, optimized, more powerful)</li>
  </ul>

  <h4>Why Use NumPy?</h4>
  <ul>
    <li>Faster than normal Python lists</li>
    <li>For working with multi-dimensional array</li>
    <li>For handling large datasets</li>
    <li>Less code for complex mathematical operations</li>
    <li>Widely used in Data Science, AI, and Machine Learning</li>
  </ul>

  <h4>Key Features of NumPy Array : </h4>
  <ul>
    <li>All elements are usually of the same data type</li>
    <li>Supports vectorized operations (no need for loops)</li>
    <li>Efficient memory usage</li>
  </ul>

  <h5> Learn More - </h5>
  <ul>
    <li>
      <a href="https://numpy.org/doc/stable/user/whatisnumpy.html" 
         target="_blank" 
         style="color:#2563eb; font-weight:bold;">
         Official NumPy Documentation
      </a>
    </li>
    <li>
      <a href="https://www.w3schools.com/python/numpy/default.asp" 
         target="_blank" 
         style="color:#2563eb; font-weight:bold;">
         W3Schools NumPy Guide
      </a>
    </li>
  </ul>   

  <h3>Getting Started -  </h3>
  <h5>Installation : </h5>
  <p><code>pip install numpy</code></p>

</div>

In [3]:
import numpy as np

In [8]:
# Checking NumPy Version
np.__version__

'2.3.2'

<p>Creating arrays - The array object in NumPy is called ndarray. We can create a NumPy ndarray object by using the <b>array()</b> function.</p>

In [ ]:
arr = np.array([2,6,7,8])   # it's a 1-D array
print(arr)
print(type(arr))

[2 6 7 8]
<class 'numpy.ndarray'>


In [ ]:
# create a 0-D array
arr = np.array(29)
print(arr)

29


In [ ]:
# creating 2-D array
arr = np.array([[1,4,5],[3,6,8]])
print(arr)

[[1 4 5]
 [3 6 8]]


<p><b>ndim</b> attribute that returns an integer that tells us how many dimensions the array have.</p>

In [ ]:
# create 3-D array
arr = np.array([[[1,3,4],[6,7,9]], [[3,1,2],[8,7,5]]])
print(arr)
print("Number of dimension: ",arr.ndim) 

[[[1 3 4]
  [6 7 9]]

 [[3 1 2]
  [8 7 5]]]
Number of dimension:  3


<p>Create an array with 5 dimensions. We can define the number of dimensions by using the <b>ndmin</b> argument.</p>

In [ ]:
arr = np.array([1,3,4,5] , ndmin = 5)
print(arr)

[[[[[1 3 4 5]]]]]


<p><b>Zeros</b> - creates array filled with 0. <br>
Syntax : np.zeros(shape, dtype=float). Here, shape → tuple (rows, cols, …). dtype → optional (default = float). </p>


In [31]:
arr = np.zeros((2,3)) # Here Shape = (2 rows, 3 columns)
print(arr)
## Example of custom data types
# arr = np.zeros((2,2), dtype=int)
# print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]


<p><b>Ones</b> - creates array filled with 1. The rest same as zeros</p>

In [28]:
arr = np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


<p><b>Full</b> - creates an array of a given shape filled with a specific value. Syntax : np.full(shape, fill_value, dtype=None)

In [29]:
arr = np.full((2,3),7)
print(arr)

[[7 7 7]
 [7 7 7]]


<p><b>Identity matrix</b> - <br>Syntax : np.identity(n, dtype=None). here, n → number of rows = columns (must be square)</p>

In [32]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<p>Custom <b>diagonal matrix</b> - </p>

In [33]:
arr = np.diag([5,5,2])
print(arr)

[[5 0 0]
 [0 5 0]
 [0 0 2]]


<p><b>np.random.rand()</b> generates an array of random numbers uniformly distributed between 0 and 1.<br>
syntax - np.random.rand(d0, d1, d2, ...)</p>

In [34]:
arr = np.random.rand(2,3)  # 2D array
print(arr)  

[[0.7470446  0.78331398 0.77800104]
 [0.67346587 0.77954433 0.23733698]]


<p><b>np.random.randint()</b> generates random integers within a specified range.<br>
syntax - np.random.randint(low, high=None, size=None, dtype=int) </p>

In [37]:
x = np.random.randint(5)   # single random num. output - (0-4)
print(x)
y = np.random.randint(10, 20) # range (low to high). output - (10-19)
print(y)

## 1D array
# arr = np.random.randint(1, 10, size=5)
# print(arr)   

## 2D array
arr = np.random.randint(3,29, size = (2,3))
print(arr)

3
15
[[22  9  9]
 [18 27  6]]


<p><b>np.arange()</b> creates a NumPy array with evenly spaced values within a given interval. It’s similar to Python’s built-in range(), but returns a NumPy array.<br>
Syntax - np.arange(start, stop, step, dtype=None).<br>
here, <br>start → starting value (default = 0)<br>stop → ending value (excluded)<br>step → gap between values (default = 1)<br>dtype → optional

In [38]:
arr = np.arange(2,9,2)
print(arr)

[2 4 6 8]


<p><b>np.linspace()</b> creates an array of evenly spaced numbers between two values, based on the number of elements, not step size.<br>Syntax - np.linspace(start, stop, num=50, endpoint=True, dtype=None).<br>here,<br>start → starting value<br>stop → ending value<br>num → number of elements (default = 50)<br>endpoint → include stop or not<br>dtype → optional</p>

In [39]:
arr = np.linspace(0,60,10)
print(arr)

[ 0.          6.66666667 13.33333333 20.         26.66666667 33.33333333
 40.         46.66666667 53.33333333 60.        ]


Explanation:

Total elements = 10
Includes both 0 and 60
Automatically calculates step

In [ ]:
# Default Behavior

arr = np.linspace(0,1)
print(arr)   # Creates 50 values between 0 and 1

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [71]:
# Excluding Endpoint
arr = np.linspace(0, 10, 5, endpoint=False)
print(arr)  # 10 is NOT included

[0. 2. 4. 6. 8.]


In [75]:
# Integer dtype
arr = np.linspace(1, 5, 4, dtype=int)
print(arr)

[1 2 3 5]


<b>Note: </b>Instead of giving step, NumPy computes:<br>
step = (stop - start) / (num - 1)<br>
(if endpoint=True)

<p>- Array Slicing -<p>

In [12]:
# 1D array 
arr = np.array([2,5,6,7,8])
print(arr[0])
print(arr[1:3])
print(arr[1:])

2
[5 6]
[5 6 7 8]


In [17]:
# 2D array
arr = np.array([[1,5,4], [4,7,9]])
print(arr[1,1])  # Think like a matrix. Row 1, Col 1
print(arr[1,:])  # row
print(arr[:,2])  # col

7
[4 7 9]
[4 9]


<p>max(), min(), argmax(), argmin()<p>

In [20]:
arr = np.array([2,7,8,9,1])
print(arr.max())
print(arr.min())
print(arr.argmax())  # Index of max value (return index)
print(arr.argmin())  # Index of min value (return index)
print(len(arr))

9
1
3
4
5


<p><b>shape</b> - It tells or sets the structure of array. It shows (rows, columns). It can also change the array directly.</p> 

In [11]:
arr = np.arange(6)
print(arr) 
arr.shape = (2,3)
print(arr)  # changes original array

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


<p><b>reshape()</b> - It returns a new array with new shape. It does not modify original array</p>

In [17]:
arr = np.arange(0,10,2)
print(arr)
matrix = arr.reshape(5,1)
print(matrix)
print(arr)  # Original still same. 

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]
[0 2 4 6 8]


**Note:** for **shape** and **reshape()** -
```bash
# Total elements must match
# Example:
# 6 elements → can be (2,3), (3,2), (1,6)
# Cannot be (4,2)
```