<h1 style="text-align:center; font-weight:bold;"> NumPy </h1>
<hr style="border: none; height: 3px; 
             background: linear-gradient(to right, #6a11cb, #2575fc);">
<div>

  <h4>What is NumPy?</h4>
  <p>
    <b>NumPy (Numerical Python)</b> is a powerful Python library used for 
    fast mathematical computations and working with arrays. It allows us to handle large datasets efficiently and perform complex calculations with minimal code.
  </p>

  <h4>Python List vs NumPy Array - </h4>
  <ul>
    <li><b>Python List:</b> Basic tool (slower, limited operations). List elements are stored separately in memory</li>
    <li><b>NumPy Array:</b> Advanced tool (faster, optimized, more powerful). NumPy stores data in one continuous block of memory</li>
  </ul>

  <h4>Why Use NumPy?</h4>
  <ul>
    <li>Faster than normal Python lists</li>
    <li>For working with multi-dimensional array</li>
    <li>For handling large datasets</li>
    <li>Less code for complex mathematical operations</li>
    <li>Widely used in Data Science, AI, and Machine Learning</li>
  </ul>

  <h4>Key Features of NumPy Array : </h4>
  <ul>
    <li>All elements are usually of the same data type</li>
    <li>Supports vectorized operations (no need for loops)</li>
    <li>Efficient memory usage</li>
  </ul>

  <h5> Learn More - </h5>
  <ul>
    <li>
      <a href="https://numpy.org/doc/stable/user/whatisnumpy.html" 
         target="_blank" 
         style="color:#2563eb; font-weight:bold;">
         Official NumPy Documentation
      </a>
    </li>
    <li>
      <a href="https://www.w3schools.com/python/numpy/default.asp" 
         target="_blank" 
         style="color:#2563eb; font-weight:bold;">
         W3Schools NumPy Guide
      </a>
    </li>
  </ul>   

  <h3>Getting Started -  </h3>
  <h5>Installation : </h5>
  <p><code>pip install numpy</code></p>

</div>

In [2]:
import numpy as np

In [8]:
# Checking NumPy Version
np.__version__

'2.3.2'

<h4><b>NumPy Array Rules : </b></h4>
<p>1. Homogeneous Data (Same Type) - All elements in a NumPy array are of the same data type. If mixed → NumPy converts automatically.<br>
Example:<br></p>

In [34]:
np.array([1, 2, 3])        # int
np.array([1, 2.5, 3])      # becomes float


array([1. , 2.5, 3. ])

<p>2. Fixed Size (Immutable Length) - Array size cannot be changed after creation. We cannot directly add/remove elements.<br>
Example:</p>

In [35]:
arr = np.array([1,2,3])
# size is fixed

<p>3. Rectangular Structure (For 2D & Higher) - All rows must have equal number of elements.</p>

```python
#  Valid
[[1, 2, 3],
 [4, 5, 6]]

#  Invalid
[[1, 2, 3],
 [4, 5]]

<p>Creating arrays - The array object in NumPy is called ndarray. We can create a NumPy ndarray object by using the <b>array()</b> function.</p>

In [ ]:
arr = np.array([2,6,7,8])   # it's a 1-D array
print(arr)
print(type(arr))

[2 6 7 8]
<class 'numpy.ndarray'>


In [ ]:
# create a 0-D array
arr = np.array(29)
print(arr)

29


In [ ]:
# creating 2-D array
arr = np.array([[1,4,5],[3,6,8]])
print(arr)

[[1 4 5]
 [3 6 8]]


<p><b>ndim</b> attribute that returns an integer that tells us how many dimensions the array have.</p>

In [ ]:
# create 3-D array
arr = np.array([[[1,3,4],[6,7,9]], [[3,1,2],[8,7,5]]])
print(arr)
print("Number of dimension: ",arr.ndim) 

[[[1 3 4]
  [6 7 9]]

 [[3 1 2]
  [8 7 5]]]
Number of dimension:  3


<p>Create an array with 5 dimensions. We can define the number of dimensions by using the <b>ndmin</b> argument.</p>

In [ ]:
arr = np.array([1,3,4,5] , ndmin = 5)
print(arr)

[[[[[1 3 4 5]]]]]


<p><b>Zeros</b> - creates array filled with 0. <br>
Syntax : np.zeros(shape, dtype=float). Here, shape → tuple (rows, cols, …). dtype → optional (default = float). </p>


In [31]:
arr = np.zeros((2,3)) # Here Shape = (2 rows, 3 columns)
print(arr)
## Example of custom data types
# arr = np.zeros((2,2), dtype=int)
# print(arr)


[[0. 0. 0.]
 [0. 0. 0.]]


<p><b>Ones</b> - creates array filled with 1. The rest same as zeros</p>

In [28]:
arr = np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


<p><b>Full</b> - creates an array of a given shape filled with a specific value. Syntax : np.full(shape, fill_value, dtype=None)

In [29]:
arr = np.full((2,3),7)
print(arr)

[[7 7 7]
 [7 7 7]]


<p><b>Identity matrix</b> - <br>Syntax : np.identity(n, dtype=None). here, n → number of rows = columns (must be square)</p>

In [32]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<p>Custom <b>diagonal matrix</b> - </p>

In [33]:
arr = np.diag([5,5,2])
print(arr)

[[5 0 0]
 [0 5 0]
 [0 0 2]]


<p><b>np.random.rand()</b> generates an array of random numbers uniformly distributed between 0 and 1.<br>
syntax - np.random.rand(d0, d1, d2, ...)</p>

In [34]:
arr = np.random.rand(2,3)  # 2D array
print(arr)  

[[0.7470446  0.78331398 0.77800104]
 [0.67346587 0.77954433 0.23733698]]


<p><b>np.random.randint()</b> generates random integers within a specified range.<br>
syntax - np.random.randint(low, high=None, size=None, dtype=int) </p>

In [37]:
x = np.random.randint(5)   # single random num. output - (0-4)
print(x)
y = np.random.randint(10, 20) # range (low to high). output - (10-19)
print(y)

## 1D array
# arr = np.random.randint(1, 10, size=5)
# print(arr)   

## 2D array
arr = np.random.randint(3,29, size = (2,3))
print(arr)

3
15
[[22  9  9]
 [18 27  6]]


<p><b>np.arange()</b> creates a NumPy array with evenly spaced values within a given interval. It’s similar to Python’s built-in range(), but returns a NumPy array.<br>
Syntax - np.arange(start, stop, step, dtype=None).<br>
here, <br>start → starting value (default = 0)<br>stop → ending value (excluded)<br>step → gap between values (default = 1)<br>dtype → optional

In [38]:
arr = np.arange(2,9,2)
print(arr)

[2 4 6 8]


<p><b>np.linspace()</b> creates an array of evenly spaced numbers between two values, based on the number of elements, not step size.<br>Syntax - np.linspace(start, stop, num=50, endpoint=True, dtype=None).<br>here,<br>start → starting value<br>stop → ending value<br>num → number of elements (default = 50)<br>endpoint → include stop or not<br>dtype → optional. Here, dtype=None means :
NumPy decides automatically. In linspace() :
It chooses float (usually float64)</p>

In [39]:
arr = np.linspace(0,60,10)
print(arr)

[ 0.          6.66666667 13.33333333 20.         26.66666667 33.33333333
 40.         46.66666667 53.33333333 60.        ]


Explanation:

Total elements = 10
Includes both 0 and 60
Automatically calculates step

In [ ]:
# Default Behavior

arr = np.linspace(0,1)
print(arr)   # Creates 50 values between 0 and 1

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [71]:
# Excluding Endpoint
arr = np.linspace(0, 10, 5, endpoint=False)
print(arr)  # 10 is NOT included

[0. 2. 4. 6. 8.]


In [75]:
# Integer dtype
arr = np.linspace(1, 5, 4, dtype=int)
print(arr)

[1 2 3 5]


<b>Note: </b>Instead of giving step, NumPy computes:<br>
step = (stop - start) / (num - 1)<br>
(if endpoint=True)

<p>- Array Slicing -<p>

In [12]:
# 1D array 
arr = np.array([2,5,6,7,8])
print(arr[0])
print(arr[1:3])
print(arr[1:])

2
[5 6]
[5 6 7 8]


In [17]:
# 2D array
arr = np.array([[1,5,4], [4,7,9]])
print(arr[1,1])  # Think like a matrix. Row 1, Col 1
print(arr[1,:])  # row
print(arr[:,2])  # col

7
[4 7 9]
[4 9]


In [6]:
# [start:end:step] in 1D
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])
print(arr[::2])  # Return every other element from the entire array

[2 4]
[1 3 5 7]


In [10]:
# [start:end:step] in 2D 
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[1,1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


<p>max(), min(), argmax(), argmin()<p>

In [20]:
arr = np.array([2,7,8,9,1])
print(arr.max())
print(arr.min())
print(arr.argmax())  # Index of max value (return index)
print(arr.argmin())  # Index of min value (return index)
print(len(arr))

9
1
3
4
5


<p><b>shape</b> - It tells or sets the structure of array. It shows (rows, columns). It can also change the array directly.</p> 

In [30]:
arr = np.arange(6)
print(arr) 
arr.shape = (2,3)
print(arr)  # changes original array

# More 
arr_2D = np.array([[1,4,5,7], [2,4,1,7]])
print(arr_2D.shape) 
# returns a tuple (2, 4) which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
(2, 4)


<p><b>reshape()</b> - It returns a new array with new shape. It does not modify original array</p>

In [17]:
arr = np.arange(0,10,2)
print(arr)
matrix = arr.reshape(5,1)
print(matrix)
print(arr)  # Original still same. 

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]
[0 2 4 6 8]


**Note:** for **shape** and **reshape()** -
```bash
# Total elements must match
# Example:
# 6 elements → can be (2,3), (3,2), (1,6)
# Cannot be (4,2)
```

<p><b>Flattening the arrays</b> - Flattening array means converting a multidimensional array into a 1D array. We can use <b>reshape(-1)</b> to do this.</p>

In [33]:
arr = np.array([[3,2,1,5,6], [3,4,6,1,8]])
print(arr)
new_arr = arr.reshape(-1)
print(new_arr)

[[3 2 1 5 6]
 [3 4 6 1 8]]
[3 2 1 5 6 3 4 6 1 8]


<p><b>Copy vs View in NumPy</b> - <br>
<b>view</b> - A view does NOT create new data. It just looks at the original array. If we change view → original array also changes.<br>
<b>Copy</b> - A copy creates a completely new array. If we change copy → original array does NOT change.</p>

In [26]:
arr = np.array([1,2,3,4,5])
view_arr = arr.view()  # Create a view (shares same memory, no new data created)
print(view_arr)   # Print view (same as original initially)

# Modify the view
view_arr[0] = 100
print(arr)    # Change is reflected in original array (because they are linked)
print(view_arr.base) # .base points to original array → proves it's a view

[1 2 3 4 5]
[100   2   3   4   5]
[100   2   3   4   5]


In [27]:
arr = np.array([1,2,3,4,5])
copy_arr = arr.copy()  # Create a copy (new memory, completely independent)
print(copy_arr)
copy_arr[0] = 100
print(arr)           # Original array remains unchanged (no shared memory)
print(copy_arr)
print(arr.base)      # .base is None → this array owns its memory (not a view)

[1 2 3 4 5]
[1 2 3 4 5]
[100   2   3   4   5]
None


<p><b>Note : Check if Array Owns its Data</b><br>
Copies owns the data, and views does not own the data, but how can we check this? Every NumPy array has the attribute <b>base</b> that returns <code>None</code> if the array owns the data. Otherwise, the <b>base</b>  attribute refers to the original object.</p>

<h5>Array Iteration in NumPy - </h5>
<p>What is Array Iteration?<br>
Array iteration means accessing each element of a NumPy array one by one. In basic Python, we use nested loops for multi-dimensional arrays, which becomes complex for higher dimensions. <br>

Using <b>np.nditer()</b><br>

`np.nditer()` is an efficient iterator that allows element-wise traversal of arrays regardless of their dimensions. It iterates over each scalar value in the array. </p>

In [51]:
arr = np.array([[1,2,3],[2,6,7]])

# Traditional method (nested loops)
# for i in arr:
#     for j in i:
#         print(j)

# Using nditer
for i in np.nditer(arr):
    print(i)

## Similar for any dimension 

1
2
3
2
6
7


<p><b>np.ndenumerate()</b> (Index + Value) - <br>
It iterates with index + element. It is best when we need position tracking.<br>
Syntax : <br></p>  

```python
for index, value in np.ndenumerate(arr):
    print(index, value)

In [52]:
arr = np.array([[1,4,5,7], [2,8,9,5]])

for idx, i in np.ndenumerate(arr):
    print(idx, i)

(0, 0) 1
(0, 1) 4
(0, 2) 5
(0, 3) 7
(1, 0) 2
(1, 1) 8
(1, 2) 9
(1, 3) 5


<p>Searching Arrays - We can search an array for a certain value, and return the indexes that get a match. To search an array, use the <b>where()</b> method.</p>

In [55]:
arr = np.array([1,5,7,4,3,2,1])
x = np.where(arr == 4)
print(x)
# return a tuple: (array([3]),) Which means that the value 4 is present at index 3

(array([3]),)


In [57]:
# Find the indexes where the values are odd

arr = np.array([2,5,6,2,1])

x = np.where(arr%2 != 0)
print(x)

(array([1, 4]),)


<p>Sorting Arrays : </p>

In [67]:
# 1D
arr = np.array([2,3,4,1,9,5])
print(np.sort(arr))  
# This method returns a copy of the array, leaving the original array unchanged. (alphabetically sort also possible)

[1 2 3 4 5 9]


In [68]:
# 2D
arr = np.array([[3,1,2], [5,0,8]])
print(np.sort(arr))

[[1 2 3]
 [0 5 8]]


<p>Array Filtering - Filtering means selecting elements from an array based on a condition.</p>

In [70]:
arr = np.array([3,5,1,2,9])

x = arr[arr > 2]
print(x) # arr > 2 creates: [True, True, False, False, True]. Only True values are selected

[3 5 9]


In [78]:
# arr = np.array([3,6,8,1,44,52,67,95,100])

# filter_arr = []

# for i in arr:
#     if i % 2 == 0:   # check for even
#         filter_arr.append(True)
#     else:
#         filter_arr.append(False)

# new_arr = arr[filter_arr]
# print(filter_arr)
# print(new_arr)  

##OR Create directly
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)      

[False  True False  True False  True False]
[2 4 6]


<p>Joining NumPy Arrays - </p>

In [8]:
arr1 = np.array([2,4,6,8])
arr2 = np.array([1,3,5,7,9])

arr = np.concatenate((arr1,arr2))
print(arr)

[2 4 6 8 1 3 5 7 9]


In [15]:
## Joining 2D Arrays using NumPy
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[3,4,5],[2,5,7]])

# axis = 1 → column-wise join (adds more columns, moves right)
arr_axis1 = np.concatenate((arr1, arr2), axis=1)

# axis = 0 → row-wise join (adds more rows, moves down)
# default axis = 0
arr_axis0 = np.concatenate((arr1, arr2))

print(arr_axis1)
print(arr_axis0)

[[1 2 3 3 4 5]
 [4 5 6 2 5 7]]
[[1 2 3]
 [4 5 6]
 [3 4 5]
 [2 5 7]]


In [19]:
arr1 = np.array([[1,2,3], [9,6,7]])
arr2 = np.array([[2,5,7], [3,1,4]])

arr_hstack = np.hstack((arr1,arr2))   # Stack columns (horizontal)
arr_vstack = np.vstack((arr1,arr2))   # Stack rows (vertical)
print(arr_hstack)
print(arr_vstack)

[[1 2 3 2 5 7]
 [9 6 7 3 1 4]]
[[1 2 3]
 [9 6 7]
 [2 5 7]
 [3 1 4]]


<p>Splitting NumPy Arrays - Splitting is reverse operation of Joining. We use <b>array_split()</b> for splitting arrays, we pass it the array we want to split and the number of splits.<br>
Syntax : np.array_split(array, number_of_splits, axis=0)</p>

In [3]:
arr = np.array([3,4,5,1,7,8])
new_arr = np.array_split(arr,3)
print(new_arr)

[array([3, 4]), array([5, 1]), array([7, 8])]


In [19]:
# Unequal Split Example
arr = np.array([2,3,4,5,6])
new_arr = np.array_split(arr, 3)
print(new_arr)
print(new_arr[1])

[array([2, 3]), array([4, 5]), array([6])]
[4 5]


In [3]:
# Split the 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[0])

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[[1 2 3]
 [4 5 6]]
